# Copyright 2026 MongoDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import List, Tuple

from ..renderer_util.io import write_text
from ..renderer_util.pgf import tikz_hrule, tikz_node
from ..renderer_util.heatmap_table import (
    CELL_FONT_PGF,
    fmt_cost_multiplier,
    fmt_min_k,
    fmt_qps,
    latex_escape,
    pgf_draw_heatmap_cell,
)

from .data import heatmap_ci_text, heatmap_value
from .core import (
    ACC_LABEL,
    CMIDRULE_KERN,
    FRONTIER_COLOR,
    HeatmapLayout,
    LoadKey,
    PolicySpec,
    row_for_load,
)


def write_unified_heatmap_pgf(
    path: str,
    policy_specs: List[PolicySpec],
    load_keys: List[LoadKey],
    layout: HeatmapLayout,
    log_floor: float,
    ci: str,
    cmap,
    norm,
    show_99_frontier: bool = False,
) -> None:
    col_widths = layout.col_widths
    col_lefts = layout.col_lefts
    total_width = layout.total_width
    num_loads = len(load_keys)

    lines = [
        "% Auto-generated by src/renderers/policy_heatmap/.",
        "% Requires \\usepackage{tikz}. Include with \\input{...} or wrap in \\noindent\\resizebox.",
        r"\begin{tikzpicture}[x=2.0cm,y=0.37cm]",
        r"\definecolor{rlsOuter}{RGB}{34,34,34}",
        r"\definecolor{rlsText}{RGB}{17,17,17}",
        r"\definecolor{rlsHeaderText}{RGB}{34,34,34}",
        r"\definecolor{rlsWhite}{RGB}{255,255,255}",
        rf"\definecolor{{rlsFrontier}}{{HTML}}{{{FRONTIER_COLOR.lstrip('#').upper()}}}",
    ]

    lines.append(
        rf"\useasboundingbox (0.000,2.000) rectangle "
        rf"({total_width:.3f},{-(num_loads + 1):.3f});"
    )

    tikz_node(
        lines,
        col_lefts[0] + (col_widths[0] / 2.0),
        -0.5,
        r"\textbf{CPU}\\\textbf{Load}",
        r"\fontsize{6.5}{6.8}\selectfont",
        "rlsHeaderText",
    )

    for spec in policy_specs:
        tikz_node(
            lines,
            (spec.block_left + spec.block_right) / 2.0,
            -1.5,
            rf"\textbf{{{latex_escape(spec.label)} Policy}}",
            r"\fontsize{6.5}{6.8}\selectfont",
            "rlsHeaderText",
        )

    for spec in policy_specs:
        if spec.show_qps:
            tikz_node(
                lines,
                (spec.qps_left + spec.qps_right) / 2.0,
                0.0,
                r"\textbf{Conc.}\\\textbf{Reads}\\\textbf{/ Sec}",
                r"\fontsize{5.4}{6.0}\selectfont",
                "rlsHeaderText",
            )
        tikz_node(
            lines,
            (spec.k_left + spec.k_right) / 2.0,
            -0.5,
            r"\textbf{$k$ (Queries Per Probe Type)}",
            r"\fontsize{6.5}{6.8}\selectfont",
            "rlsHeaderText",
        )
        if spec.show_summary and not spec.show_cost:
            tikz_node(
                lines,
                (spec.cost_left + spec.cost_right) / 2.0,
                0.0,
                r"\textbf{$k$ @ $\geq$}\\\textbf{" + ACC_LABEL + r"\% acc}\\\textbf{Within CI}",
                r"\fontsize{5.8}{6.2}\selectfont",
                "rlsHeaderText",
            )
        elif spec.show_summary:
            tikz_node(
                lines,
                (spec.cost_left + spec.cost_right) / 2.0,
                -0.5,
                r"\textbf{@ $\geq$ " + ACC_LABEL + r"\% acc}",
                r"\fontsize{5.8}{6.2}\selectfont",
                "rlsHeaderText",
            )

    for spec in policy_specs:
        for k_idx, k in enumerate(spec.k_values):
            col_idx = spec.k_start + k_idx
            tikz_node(
                lines,
                col_lefts[col_idx] + (col_widths[col_idx] / 2.0),
                0.5,
                latex_escape(str(k)),
                r"\fontsize{5.6}{6.0}\selectfont",
                "rlsHeaderText",
            )
        if spec.show_summary and spec.show_cost:
            tikz_node(
                lines,
                col_lefts[spec.min_k_col] + (col_widths[spec.min_k_col] / 2.0),
                0.5,
                r"\textbf{$k$}",
                r"\fontsize{5.8}{6.2}\selectfont",
                "rlsHeaderText",
            )
            tikz_node(
                lines,
                col_lefts[spec.cost_col] + (col_widths[spec.cost_col] / 2.0),
                0.5,
                r"\textbf{Queries}\\\textbf{Per Probe ($3k$)}",
                r"\fontsize{5.0}{5.4}\selectfont",
                "rlsHeaderText",
            )

    color_idx = 0
    for row_idx, load_key in enumerate(load_keys):
        y = float(row_idx + 1)
        load_label = load_key[0]
        for spec in policy_specs:
            row = row_for_load(spec.rows, load_key)
            if row is not None:
                load_label = row.scenario
                break
        tikz_node(
            lines,
            col_lefts[0] + (col_widths[0] / 2.0),
            y + 0.5,
            latex_escape(load_label),
            r"\fontsize{6.5}{7.0}\selectfont",
            "rlsText",
        )

        for spec in policy_specs:
            row = row_for_load(spec.rows, load_key)
            if spec.show_qps:
                qps_text = fmt_qps(row.actual_total_qps) if row is not None else "---"
                tikz_node(
                    lines,
                    col_lefts[spec.qps_col] + (col_widths[spec.qps_col] / 2.0),
                    y + 0.5,
                    latex_escape(qps_text),
                    CELL_FONT_PGF,
                    "rlsText",
                )

            if row is None and spec.missing_message_lines:
                pgf_lines = r"\\".join(
                    rf"\textit{{{latex_escape(line)}}}"
                    for line in spec.missing_message_lines
                )
                tikz_node(
                    lines,
                    (spec.k_left + spec.k_right) / 2.0,
                    y + 0.5,
                    pgf_lines,
                    r"\fontsize{5.4}{5.8}\selectfont",
                    "rlsText",
                )
            else:
                for k_idx, k in enumerate(spec.k_values):
                    col_idx = spec.k_start + k_idx
                    left = col_lefts[col_idx]
                    width = col_widths[col_idx]
                    value = heatmap_value(row, k, "accuracy") if row is not None else None
                    if value is None:
                        tikz_node(lines, left + width / 2.0, y + 0.5, "---", CELL_FONT_PGF, "rlsText")
                    else:
                        assert row is not None
                        ci_text = heatmap_ci_text(row, k, ci) if ci != "none" else ""
                        color_idx = pgf_draw_heatmap_cell(
                            lines,
                            left,
                            y,
                            width,
                            float(value),
                            ci_text or None,
                            cmap,
                            norm,
                            color_idx,
                            log_floor,
                            ci_show=(ci != "none"),
                        )

            if spec.show_summary:
                min_k_label = fmt_min_k(row.min_k_99_accuracy) if row is not None else "---"
                cost_label = (
                    fmt_cost_multiplier(row.query_cost_multiplier_at_min_k_99)
                    if row is not None
                    else "---"
                )
                tikz_node(
                    lines,
                    col_lefts[spec.min_k_col] + (col_widths[spec.min_k_col] / 2.0),
                    y + 0.5,
                    latex_escape(min_k_label),
                    CELL_FONT_PGF,
                    "rlsText",
                )
                if spec.show_cost:
                    tikz_node(
                        lines,
                        col_lefts[spec.cost_col] + (col_widths[spec.cost_col] / 2.0),
                        y + 0.5,
                        latex_escape(cost_label),
                        r"\fontsize{5.6}{6.0}\selectfont",
                        "rlsText",
                    )

    if show_99_frontier:
        for spec in policy_specs:
            points: List[Tuple[float, float]] = []
            for row_idx, load_key in enumerate(load_keys):
                row = row_for_load(spec.rows, load_key)
                if row is None:
                    continue
                min_k_val = row.min_k_99_accuracy
                if min_k_val is None:
                    continue
                try:
                    k_idx = spec.k_values.index(min_k_val)
                except ValueError:
                    continue
                x = col_lefts[spec.k_start + k_idx]
                y_top = float(row_idx + 1)
                y_bot = float(row_idx + 2)
                points.append((x, y_top))
                points.append((x, y_bot))
            if points:
                frontier_path = " -- ".join(f"({px:.3f},{-py:.3f})" for px, py in points)
                lines.append(
                    rf"\draw[rlsFrontier, line width=1.0pt, line cap=butt, line join=miter] {frontier_path};"
                )

    tikz_hrule(lines, -2.0, 0.0, total_width, "0.7pt")
    for spec in policy_specs:
        tikz_hrule(
            lines,
            -1.0,
            spec.block_left + CMIDRULE_KERN,
            spec.block_right - CMIDRULE_KERN,
            "0.5pt",
        )
    for spec in policy_specs:
        tikz_hrule(
            lines,
            0.0,
            spec.k_left + CMIDRULE_KERN,
            spec.k_right - CMIDRULE_KERN,
            "0.4pt",
        )
        if spec.show_summary and spec.show_cost:
            tikz_hrule(
                lines,
                0.0,
                spec.cost_left + CMIDRULE_KERN,
                spec.cost_right - CMIDRULE_KERN,
                "0.4pt",
            )

    last_idx = len(policy_specs) - 1
    for spec_idx, spec in enumerate(policy_specs):
        left = 0.0 if spec_idx == 0 else spec.block_left
        right = total_width if spec_idx == last_idx else spec.block_right
        tikz_hrule(lines, 1.0, left, right, "0.4pt")
    tikz_hrule(lines, float(num_loads + 1), 0.0, total_width, "0.7pt")

    lines.append(r"\end{tikzpicture}")
    write_text(path, "\n".join(lines) + "\n")
